## create a dataframe with three of the optional themes

In [2]:
import pandas as pd
import requests 
import json

## Cat DF

In [3]:
cat_requests = requests.get('https://cat-fact.herokuapp.com/facts')

In [4]:
print("cat_requests:",cat_requests.status_code)

cat_requests: 200

In [5]:
results = cat_requests.json()
#results

In [6]:
pd.set_option("display.max_rows", 0)
#Getting the list of dictionnaries into the dataframe
data = pd.DataFrame(results)
data.head(10)

,status,_id,user,text,__v,source,updatedAt,type,createdAt,deleted,used
0,"{'verified': True, 'sentCount': 1}",58e008780aac31001185ed05,58e007480aac31001185ecef,Owning a cat can reduce the risk of stroke and...,0,user,2020-08-23T20:20:01.611Z,cat,2018-03-29T20:20:03.844Z,False,False
1,"{'verified': True, 'sentCount': 1}",58e009390aac31001185ed10,58e007480aac31001185ecef,"Most cats are lactose intolerant, and milk can...",0,user,2020-08-23T20:20:01.611Z,cat,2018-03-04T21:20:02.979Z,False,False
2,"{'verified': True, 'sentCount': 1}",588e746706ac2b00110e59ff,588e6e8806ac2b00110e59c3,Domestic cats spend about 70 percent of the da...,0,user,2020-08-26T20:20:02.359Z,cat,2018-01-14T21:20:02.750Z,False,True
3,"{'verified': True, 'sentCount': 1}",58e008ad0aac31001185ed0c,58e007480aac31001185ecef,The frequency of a domestic cat's purr is the ...,0,user,2020-08-24T20:20:01.867Z,cat,2018-03-15T20:20:03.281Z,False,True
4,"{'verified': True, 'sentCount': 1}",58e007cc0aac31001185ecf5,58e007480aac31001185ecef,Cats are the most popular pet in the United St...,0,user,2020-08-23T20:20:01.611Z,cat,2018-03-01T21:20:02.713Z,False,False

In [ ]:
# def flatten_column(data, column_name):
    flattened = pd.DataFrame(dict(data[column_name])).transpose()
    columns = [str(col) for col in flattened.columns]
    flattened.columns = [column_name + '_' + colname for colname in columns]
    data = pd.concat([data, flattened], axis=1)
    data = data.drop(column_name, axis=1)
    return data

data1 = flatten_column(data, 'status')
data1

## Public Holidays NL

In [9]:
#/api/v3/PublicHolidays/{Year}/{CountryCode}

In [11]:
pholiday_response = requests.get ('https://date.nager.at/api/v3/publicholidays/2023/NL')
print("Public Holiday:", pholiday_response.status_code)

Public Holiday: 200

In [14]:
results = pholiday_response.json()
#results

In [15]:
pd.set_option("display.max_rows", 0)
data = pd.DataFrame(results)
data.head(10)

,date,localName,name,countryCode,fixed,global,counties,launchYear,types
0,2023-01-01,Nieuwjaarsdag,New Year's Day,NL,True,True,None,1967.0,[Public]
1,2023-04-07,Goede Vrijdag,Good Friday,NL,False,True,None,NaN,[Public]
2,2023-04-09,Eerste Paasdag,Easter Sunday,NL,False,True,None,NaN,[Public]
3,2023-04-10,Tweede Paasdag,Easter Monday,NL,False,True,None,1642.0,[Public]
4,2023-04-27,Koningsdag,King's Day,NL,True,True,None,NaN,[Public]
5,2023-05-05,Bevrijdingsdag,Liberation Day,NL,True,True,None,1945.0,"[School, Authorities]"
6,2023-05-18,Hemelvaartsdag,Ascension Day,NL,False,True,None,NaN,[Public]
7,2023-05-28,Eerste Pinksterdag,Pentecost,NL,False,True,None,NaN,[Public]
8,2023-05-29,Tweede Pinksterdag,Whit Monday,NL,False,True,None,NaN,[Public]
9,2023-12-25,Eerste Kerstdag,Christmas Day,NL,True,True,None,NaN,[Public]

## Harry Potter Characters

In [18]:
hpc = requests.get ('https://hp-api.onrender.com/api/characters')

In [20]:
print("harry potter characters:", hpc.status_code)

harry potter characters: 200

In [22]:
results = hpc.json()
#results

In [23]:
pd.set_option("display.max_rows", 0)
data = pd.DataFrame(results)
data.head(10)

,id,name,alternate_names,species,gender,house,dateOfBirth,yearOfBirth,wizard,ancestry,eyeColour,hairColour,wand,patronus,hogwartsStudent,hogwartsStaff,actor,alternate_actors,alive,image
0,9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8,Harry Potter,"[The Boy Who Lived, The Chosen One, Undesirabl...",human,male,Gryffindor,31-07-1980,1980.0,True,half-blood,green,black,"{'wood': 'holly', 'core': 'phoenix tail feathe...",stag,True,False,Daniel Radcliffe,[],True,https://ik.imagekit.io/hpapi/harry.jpg
1,4c7e6819-a91a-45b2-a454-f931e4a7cce3,Hermione Granger,"[Hermy, Know-it-all, Miss Grant, Herm-own-ninny]",human,female,Gryffindor,19-09-1979,1979.0,True,muggleborn,brown,brown,"{'wood': 'vine', 'core': 'dragon heartstring',...",otter,True,False,Emma Watson,[],True,https://ik.imagekit.io/hpapi/hermione.jpeg
2,c3b1f9a5-b87b-48bf-b00d-95b093ea6390,Ron Weasley,"[Dragomir Despard, Ronald, Ickle Ronniekins, R...",human,male,Gryffindor,01-03-1980,1980.0,True,pure-blood,blue,red,"{'wood': 'willow', 'core': 'unicorn tail hair'...",Jack Russell terrier,True,False,Rupert Grint,[],True,https://ik.imagekit.io/hpapi/ron.jpg
3,af95bd8a-dfae-45bb-bc69-533860d34129,Draco Malfoy,[],human,male,Slytherin,05-06-1980,1980.0,True,pure-blood,grey,blonde,"{'wood': 'hawthorn', 'core': 'unicorn tail hai...",,True,False,Tom Felton,[],True,https://ik.imagekit.io/hpapi/draco.jpg
4,ca3827f0-375a-4891-aaa5-f5e8a5bad225,Minerva McGonagall,[],human,female,Gryffindor,04-10-1925,1925.0,True,half-blood,,black,"{'wood': 'fir', 'core': 'dragon heartstring', ...",tabby cat,False,True,Dame Maggie Smith,[],True,https://ik.imagekit.io/hpapi/mcgonagall.jpg
5,d5c4daa3-c726-426a-aa98-fb40f3fba816,Cedric Diggory,[],human,male,Hufflepuff,None,1977.0,True,,grey,brown,"{'wood': 'ash', 'core': 'unicorn hair', 'lengt...",,True,False,Robert Pattinson,[],False,https://ik.imagekit.io/hpapi/cedric.png
6,8f9aa40b-5d7c-441e-ad32-4564ecda3b70,Cho Chang,[],human,female,Ravenclaw,07-04-1979,1979.0,True,,brown,black,"{'wood': '', 'core': '', 'length': None}",swan,True,False,Katie Leung,[],True,https://ik.imagekit.io/hpapi/cho.jpg
7,3569d265-bd27-44d8-88e8-82fb0a848374,Severus Snape,"[Half-Blood Prince, Snivellus, Sev]",human,male,Slytherin,09-01-1960,1960.0,True,half-blood,black,black,"{'wood': '', 'core': '', 'length': None}",doe,False,True,Alan Rickman,[],False,https://ik.imagekit.io/hpapi/snape.jpg
8,36bfefd0-e0bb-4d11-be98-d1ef6117a77a,Rubeus Hagrid,"[Professor Hagrid, Hagger]",half-giant,male,Gryffindor,06-12-1928,1928.0,True,half-blood,black,black,"{'wood': 'oak', 'core': '', 'length': 16}",,False,True,Robbie Coltrane,[],True,https://ik.imagekit.io/hpapi/hagrid.png
9,3db6dc51-b461-4fa4-a6e4-b1ff352221c5,Neville Longbottom,[],human,male,Gryffindor,30-07-1980,1980.0,True,pure-blood,,blonde,"{'wood': 'cherry', 'core': 'unicorn tail hair'...",Non-Corporeal,True,False,Matthew Lewis,[],True,https://ik.imagekit.io/hpapi/neville.jpg